"""create book_embeddings table

Revision ID: 3b5b14c7f59a
Revises: 
Create Date: 2025-11-02 12:47:19.456646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '3b5b14c7f59a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_embeddings_book_id'), 'book_embeddings', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_embeddings_id'), 'book_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_embeddings_id'), table_name='book_embeddings')
    op.drop_index(op.f('ix_book_embeddings_book_id'), table_name='book_embeddings')
    op.drop_table('book_embeddings')
    # ### end Alembic commands ###
